"""Publish local, measured display-asset metadata; exclude incomplete ship geometry."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
assets = ROOT / "web_gui/assets/models"
bounds = json.loads((assets / "bounds.json").read_text())
manifest = json.loads((assets / "targets/asset-manifest.json").read_text())
catalog = {}
for item in manifest["assets"]:
    if item["download_status"] != "downloaded" or item["id"] == "ferry_roro":
        continue  # Official description: stern section only, not a whole target vessel.
    name = "targets/" + item["file"]
    measured = bounds[name]
    low, high = measured["bounds_min"], measured["bounds_max"]
    catalog[item["id"]] = {
        "id": item["id"],
        "label": item["display_name"],
        "url": "/static/assets/models/" + name,
        "type": item["type"],
        "beam": measured["size"][0],
        "length": measured["size"][2],
        "height": measured["size"][1],
        "centerX": (low[0] + high[0]) / 2,
        "centerZ": (low[2] + high[2]) / 2,
        "waterlineY": low[1] + measured["size"][2] * 0.035,
        "waterlineNote": "estimated display waterline",
        "forward": "+z",
        "license": item["license"],
        "sha256": item["sha256"],
        "source": item["source_page"],
    }
catalog["fcb45"] = {
    "id": "fcb45",
    "label": "FCB45 · reference-refined visual model v1",
    "url": "/static/assets/models/fcb45/ownship-v1.glb",
    "type": "ownship",
    "beam": 8,
    "length": 45,
    "height": bounds["fcb45/ownship-v1.glb"]["size"][1],
    "centerX": 0,
    "centerZ": 0,
    "waterlineY": 0,
    "waterlineNote": "supplied midship design waterline",
    "forward": "-z",
    "source": "User supplied FCB45 v0; reference-refined v1, 2026-09-21",
    "license": "user-provided",
    "sha256": bounds["fcb45/ownship-v1.glb"]["sha256"],
}
(assets / "catalog.json").write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n")
(ROOT / "web_gui/modules/vessel-assets.js").write_text(
    "// Generated by tools/web_3d/build_model_catalog.py. Display assets only.\nexport const VESSEL_ASSETS = Object.freeze("
    + json.dumps(catalog, indent=2, ensure_ascii=False)
    + ");\n"
)
